-- Mensajes del formulario "Contáctenos" (hermanos) y respuestas de administración
CREATE TABLE IF NOT EXISTS public.contacto_mensaje (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  nombre varchar(120) NOT NULL,
  apellido varchar(120) NOT NULL,
  email varchar(255) NOT NULL,
  mensaje text NOT NULL,
  estado varchar(20) NOT NULL DEFAULT 'nuevo' CHECK (estado IN ('nuevo', 'respondido')),
  respuesta text,
  responded_at timestamptz,
  responded_by uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contacto_mensaje_estado ON public.contacto_mensaje (estado);
CREATE INDEX IF NOT EXISTS idx_contacto_mensaje_created ON public.contacto_mensaje (created_at DESC);
