-- Catálogo de cuerpos: sigla, nombre (cuerpo), localidad.
-- Fuente: planilla capturada en assets del proyecto.
-- Re-ejecutable: actualiza nombre y localidad si la sigla ya existe.

INSERT INTO public.cuerpo (sigla, cuerpo, localidad, status)
VALUES
  ('LP04', 'CATAMARCA DEL IGUAZU', 'Misiones', 1),
  ('LP08', 'LUZ', 'Mendoza', 1),
  ('LP12', 'RESPLANDOR', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP13', 'DEBER', 'Pergamino', 1),
  ('LP14', 'CONCORDIA', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP21', 'LUMEN', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP25', 'DEL PRONUNCIAMIENTO', 'Concordia', 1),
  ('LP30', 'HERMES TRISMEGISTO', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP31', 'FRATERNIDAD', 'La Plata', 1),
  ('LP33', 'INMORTALIDAD', 'L. P. - Mercadito N° 13', 1),
  ('LP38', 'CABALLEROS TEUTONES', 'Villa General Belgrano', 1),
  ('LP39', 'UNION DEL NORTE', 'Jujuy', 1),
  ('LP44', 'ESTRELLA DEL NORTE', 'Formosa', 1),
  ('LP45', 'DEL TUCUMAN', 'Tucumán', 1),
  ('LP46', 'ESTRELLA DEL SUR', 'Comodoro Rivadavia', 1),
  ('LP47', 'AUSTRALIS HOMINE', 'Ushuaia', 1),
  ('LP48', 'SANTIAGO DEL ESTERO', 'Santiago del Estero', 1),
  ('LP50', 'SANTIAGO DERQUI', 'San Nicolás', 1),
  ('LP51', 'MATEMATICOS DE LEON', 'San Rafael', 1),
  ('LP52', 'POSTA DE YATAY', 'Salta', 1),
  ('LP53', 'SAN MARTIN', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP54', 'LA FRATERNIDAD 1877', 'Concepción del Uruguay', 1),
  ('LP55', 'SIMON BOLIVAR', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP56', 'CABALLEROS DE LA ROSA', 'Río Gallegos', 1),
  ('LP57', 'ESTRELLA DEL PILAR', 'Pilar', 1),
  ('LP59', 'AMANECER', 'Valle Viejo', 1),
  ('LP63', 'HIJOS DEL SILENCIO', 'Neuquén', 1),
  ('LP64', 'POSTA DEL SUR', 'Bahía Blanca', 1),
  ('LP65', 'LUCES LUMINOSAS', 'San Luis', 1),
  ('LP66', 'SER POR LIBRE', 'Ituzaingó', 1),
  ('LP67', 'UNION REPUBLICANA', 'Rosario', 1),
  ('LP68', 'FRANCISCO DE MIRANDA', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP69', 'ESTRELLA', 'Remedios de Escalada', 1),
  ('LP71', 'FRATERNIDAD', 'Mar del Plata', 1),
  ('LP72', 'SIERRA', 'Córdoba', 1),
  ('LP73', 'JOAQUIN V. GONZALEZ', 'Lomas de Zamora', 1),
  ('LP74', 'OBREROS DE LA PIEDRA', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP75', 'DEMOCRACIA', 'Mendoza', 1),
  ('LP76', 'AGUILAS DE LA PATAGONIA', 'Bariloche', 1),
  ('LP77', 'EL OLIVO', 'Ciudad Autónoma de Buenos Aires', 1),
  ('LP78', '11092 AF RMN', 'Rawson', 1),
  ('LP79', 'SAN MARTIN', 'Posadas', 1),
  ('LP80', 'TARAGUI', 'Corrientes', 1),
  ('LP81', 'ALBERT PIKE', 'Virasoro', 1),
  ('LP82', 'EL GENESIS', 'Malargüe', 1),
  ('CAP01', 'ANIBAL GUARDIA', 'Rosario', 1),
  ('CAP02', 'ESTRELLA DE TUCUMAN', 'San Miguel de Tucumán', 1),
  ('CAP03', 'CONCORDIA', 'Ciudad Autónoma de Buenos Aires', 1),
  ('CAP04', 'LUZ', 'Mendoza', 1),
  ('CAP07', 'LA PAZ', 'Lomas de Zamora', 1),
  ('CAP08', 'SAN MARTIN', 'Olivos', 1),
  ('CAP13', 'RAMON MATARAZZO', 'Posadas', 1),
  ('CAP16', 'UNION Y PROGRESO', 'Villa Domínico', 1),
  ('CAP17', 'GRAN REUNION AMERICANA', 'Ciudad Autónoma de Buenos Aires', 1),
  ('CAP20', 'FRATERNIDAD', 'Mar del Plata', 1),
  ('CAP21', 'SAN MARTIN', 'Venado Tuerto', 1),
  ('CAP23', 'PARAGUAY', 'Paraná', 1),
  ('CAP25', 'UNION AMERICANA', 'Salta', 1),
  ('CAP27', 'BELGRANO', 'Resistencia', 1),
  ('CAP28', 'PERLAS Y CAÑAS', 'Córdoba', 1),
  ('CAP29', 'GENARO RAMON QUADRIAGA', 'Corrientes', 1),
  ('CAP30', 'RAMON TRUAN', 'Paso de los Libres', 1),
  ('CAP31', 'HERMES TRISMEGISTO', 'Ciudad Autónoma de Buenos Aires', 1),
  ('CAP44', 'NICASIO OROÑO', 'Santa Fe', 1),
  ('CAP45', 'UNION Y VIRTUD', 'Córdoba', 1),
  ('CAP46', 'CONSTRUCTORES', 'Ciudad Autónoma de Buenos Aires', 1),
  ('CAP47', 'GERMAN MARIANUCCI', 'San Carlos de Bariloche', 1),
  ('CAP48', 'CORDOBA 1887', 'Córdoba', 1),
  ('CAP49', 'ALBERT PIKE', 'Bella Vista', 1),
  ('CAP50', 'SAN PEDRO', 'San Salvador de Jujuy', 1),
  ('CAP52', 'TRES DE FEBRERO', 'Ituzaingó', 1),
  ('CAP53', 'FENIX', 'La Plata', 1),
  ('CAP54', 'PROVINCIAS UNIDAS', 'Río Gallegos - Virtual', 1),
  ('CAP56', 'JOAQUIN V. GONZALEZ', 'La Rioja y Catamarca', 1),
  ('CAP57', 'HEREDEROS DE LA MEMORIA', 'San Rafael', 1),
  ('CAP58', 'EDUARDO HOLMBERG', 'Ituzaingó', 1),
  ('CAP59', 'FRATERNIDAD', 'Mar del Plata', 1),
  ('CAP60', 'MANUEL BELGRANO', 'Pilar', 1),
  ('CAP61', 'FORMOSA', 'Formosa', 1),
  ('CAP62', 'LOS INSURRECTOS', 'San Fernando del Valle de Catamarca', 1),
  ('ARE01', 'DEL LITORAL', 'Rosario', 1),
  ('ARE02', 'ZURICH', 'Ciudad Autónoma de Buenos Aires', 1),
  ('ARE03', 'JOSE HERNANDEZ', 'Mendoza', 1),
  ('ARE04', 'FRATERNIDAD', 'Paraná', 1),
  ('ARE06', 'SIERRA', 'Córdoba', 1),
  ('ARE07', 'ALBERT PIKE', 'Olivos', 1),
  ('ARE08', 'MITRE', 'Mar del Plata', 1),
  ('ARE09', 'GRAN CHACO AUSTRAL', 'Chaco - Formosa - Salta - Jujuy', 1),
  ('ARE10', 'JOSE HERNANDEZ', 'Corrientes - Misiones', 1),
  ('ARE11', 'SARMIENTO', 'Lomas de Zamora', 1),
  ('ARE12', 'CABALLEROS DEL TEMPLE', 'Ciudad Autónoma de Buenos Aires', 1),
  ('ARE13', 'DEL NOA', 'Salta', 1),
  ('ARE14', 'LOS INSURRECTOS', 'Santa Fe', 1),
  ('ARE15', 'SINERGIA', 'Comodoro Rivadavia - Virtual', 1),
  ('ARE16', 'SARMIENTO', 'Santiago del Estero', 1),
  ('CON01', 'BUENOS AIRES', 'Ciudad Autónoma de Buenos Aires', 1),
  ('CON02', 'DEL LITORAL', 'Rosario', 1),
  ('CON03', 'DEL PARANA', 'Paraná', 1),
  ('CON04', 'LIBERTADOR', 'Corrientes y Misiones', 1),
  ('CON05', 'ALBERT PIKE', 'Resistencia', 1),
  ('CON06', 'ARQUITECTO DEL SUEÑO', 'Mar del Plata', 1),
  ('CON07', 'DE CUYO', 'Mendoza', 1),
  ('CON08', 'DEL NOR', 'Tucumán', 1),
  ('CON09', 'ALBERT PIKE', 'Ciudad Autónoma de Buenos Aires', 1),
  ('GIG01', 'IGNACIO VIVAS', 'Ciudad Autónoma de Buenos Aires', 1),
  ('GIG02', 'URQUIZA', 'Paraná', 1),
  ('GIG03', 'ALBERT PIKE 3', 'Rosario', 1),
  ('GIG04', 'ALBERT PIKE 4', 'Ciudad Autónoma de Buenos Aires', 1),
  ('GIG05', 'NACIONAL VIRTUAL 1', 'Virtual', 1)
ON CONFLICT (sigla) DO UPDATE SET
  cuerpo = EXCLUDED.cuerpo,
  localidad = EXCLUDED.localidad,
  status = EXCLUDED.status;

NOTIFY pgrst, 'reload schema';
