-- SCG33 - Schema inicial para Supabase (PostgreSQL)
-- Auth: Supabase Auth (email + password). Datos extra del hermano en public.profiles.

-- Grupos / roles (Grado 4, Grado 33, Admin, etc.)
CREATE TABLE IF NOT EXISTS public.user_groups (
  id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_name varchar(150) NOT NULL,
  group_level smallint NOT NULL UNIQUE,
  group_status smallint NOT NULL DEFAULT 1
);

INSERT INTO public.user_groups (group_name, group_level, group_status) VALUES
  ('Admin', 1, 1),
  ('Special', 2, 1),
  ('User', 3, 1),
  ('Grado 4', 4, 1),
  ('Grado 9', 9, 1),
  ('Grado 14', 14, 1),
  ('Grado 18', 18, 1),
  ('Grado 19', 19, 1),
  ('Grado 24', 24, 1),
  ('Grado 30', 30, 1),
  ('Grado 31', 31, 1),
  ('Grado 32', 32, 1),
  ('Grado 33', 33, 1)
ON CONFLICT (group_level) DO NOTHING;

-- Cuerpos escocistas
CREATE TABLE IF NOT EXISTS public.cuerpo (
  id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sigla varchar(60) NOT NULL UNIQUE,
  cuerpo varchar(255) NOT NULL,
  localidad varchar(255) DEFAULT '',
  trabajos varchar(255) DEFAULT '',
  observaciones varchar(255) DEFAULT '',
  status smallint NOT NULL DEFAULT 1,
  folder varchar(255) DEFAULT NULL,
  presidente varchar(255) DEFAULT NULL,
  secretario varchar(255) DEFAULT NULL,
  tesorero varchar(255) DEFAULT NULL
);

-- Otros Orientes
CREATE TABLE IF NOT EXISTS public.otros_orientes (
  id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  pais varchar(100) NOT NULL,
  web varchar(255) DEFAULT NULL,
  direccion varchar(255) DEFAULT NULL,
  mail_institucional varchar(255) DEFAULT NULL,
  telefono varchar(50) DEFAULT NULL,
  soberano varchar(255) DEFAULT NULL
);

-- Perfil del hermano (vinculado a auth.users)
-- El email para login está en auth.users; aquí el resto de datos.
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name varchar(60) NOT NULL DEFAULT '',
  apellido varchar(60) NOT NULL DEFAULT '',
  user_level smallint NOT NULL DEFAULT 3 REFERENCES public.user_groups(group_level),
  grado smallint NOT NULL DEFAULT 0,
  cuerpo_id smallint REFERENCES public.cuerpo(id) ON DELETE SET NULL,
  telefono varchar(20) DEFAULT NULL,
  profesion varchar(60) DEFAULT NULL,
  hist_grado varchar(120) DEFAULT NULL,
  direccion varchar(120) DEFAULT NULL,
  observaciones varchar(255) DEFAULT NULL,
  image varchar(255) DEFAULT 'no_image.jpg',
  status smallint NOT NULL DEFAULT 1,
  last_login timestamptz DEFAULT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Ver propio perfil
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

-- Solo admins pueden ver todos los perfiles (se usa service role en API para admin)
-- Política para que admins (user_level=1) puedan ver/actualizar otros (vía service role, RLS no aplica)

-- Trigger: crear perfil al registrar usuario (con metadata)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, name, apellido, user_level, grado)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'name', ''),
    COALESCE(NEW.raw_user_meta_data ->> 'apellido', ''),
    COALESCE((NEW.raw_user_meta_data->>'user_level')::smallint, 3),
    COALESCE((NEW.raw_user_meta_data->>'grado')::smallint, 0)
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Carpetas por rol mínimo (biblioteca/descargas)
CREATE TABLE IF NOT EXISTS public.carpetas_roles (
  id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nom_carpeta varchar(255) NOT NULL UNIQUE,
  rol_minimo varchar(50) NOT NULL
);

-- Trámites en línea
CREATE TABLE IF NOT EXISTS public.tramites (
  id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo varchar(20) NOT NULL CHECK (tipo IN ('ingreso','reingreso','ascenso','dimision','pase')),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  nombre varchar(120) NOT NULL,
  apellido varchar(120) NOT NULL,
  mail varchar(255) DEFAULT NULL,
  cuerpo varchar(255) NOT NULL,
  cuerpo_pasa varchar(255) DEFAULT NULL,
  plomo varchar(5) DEFAULT 'NO',
  fecha_propuesta varchar(50) DEFAULT NULL,
  datos_json text,
  estado varchar(50) DEFAULT 'pendiente',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tramites_adjuntos (
  id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tramite_id smallint NOT NULL REFERENCES public.tramites(id) ON DELETE CASCADE,
  nombre_original varchar(255) NOT NULL,
  ruta varchar(512) NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Archivos / biblioteca (metadata; el archivo va en Storage)
CREATE TABLE IF NOT EXISTS public.file (
  id smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code varchar(12) NOT NULL UNIQUE,
  filename varchar(255) NOT NULL,
  description varchar(255) DEFAULT '',
  download_count int NOT NULL DEFAULT 0,
  is_public boolean NOT NULL DEFAULT false,
  is_folder boolean NOT NULL DEFAULT false,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  folder_id smallint REFERENCES public.file(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_profiles_user_level ON public.profiles(user_level);
CREATE INDEX IF NOT EXISTS idx_profiles_cuerpo_id ON public.profiles(cuerpo_id);
CREATE INDEX IF NOT EXISTS idx_tramites_user_id ON public.tramites(user_id);
